main: sotumney.blockbedrockboats
name: BlockBedrockBoats
version: "0.1"
api-version: "1.21.1"
author: Sotumney
description: An extremely barebones plugin to block Bedrock players joining a Java server.
commands:
  togglebedrockblock:
    description: Toggles whether players can connect using Geyser through Floodgate.
    usage: "Just put the command in bro"
permissions:
  blockbedrockboats.allowtoggle:
    description: Gives permission whether a user can use commands from this plugin.
    default: op
